# Generated by Django 3.0.4 on 2020-04-07 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('image_filter', models.CharField(choices=[('normal', 'Normal'), ('_1977', '1977'), ('aden', 'Aden'), ('brannan', 'Brannan'), ('brooklyn', 'Brooklyn'), ('clarendon', 'Clarendon'), ('earlybird', 'Earlybird'), ('gingham', 'Gingham'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('kelvin', 'Kelvin'), ('lark', 'Lark'), ('lofi', 'Lo-Fi'), ('maven', 'Maven'), ('mayfair', 'Mayfair'), ('moon', 'Moon'), ('nashville', 'Nashville'), ('perpetua', 'Perpetua'), ('reyes', 'Reyes'), ('rise', 'Rise'), ('slumber', 'Slumber'), ('stinson', 'Stinson'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('willow', 'Willow'), ('xpro2', 'X-pro II')], default='normal', max_length=15)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='faketagram_photos.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
