# Generated by Django 3.0.4 on 2020-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='defaults/photos/default_profile_photo.png', upload_to='photos/profile_photos/%Y/%m/%d'),
        ),
    ]
