# Generated by Django 3.0.4 on 2020-04-02 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
