# Generated by Django 3.0.4 on 2020-04-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
