# Generated by Django 3.0.4 on 2020-04-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faketagram_follows', '0001_initial'),
        ('faketagram_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faketagram_follows.UserFollow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FollowNotification',
        ),
    ]
