# Generated by Django 3.0.4 on 2020-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faketagram_notifications', '0002_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('F', 'Follow')], default=None, max_length=5),
            preserve_default=False,
        ),
    ]
