# Generated by Django 3.0.4 on 2020-04-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faketagram_accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
